ServerlessCN:
  component: '@serverless/tencent-website'
  inputs:
    code:
      src: ./public
      index: index.html
      error: index.html
    region: ap-guangzhou
    bucketName: serverlesscloud
