name: Release ServerlessCN CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install serverless framework
        run: npm install -g serverless
      - name: create .env And inject secrets
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: |
          touch .env
          echo TENCENT_SECRET_ID=$TENCENT_SECRET_ID >> .env
          echo TENCENT_SECRET_KEY=$TENCENT_SECRET_KEY >> .env
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: deploy
        run: sls --debug
